run:
  timeout: 5m
  skip-dirs:
    - data
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: benchmark_test\.go
      linters:
        - errcheck
